version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mychat_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: y
      POSTGRES_DB: mychat
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql